### PR TITLE
Use the correct fonts

### PR DESCRIPTION
**Pull request by mathiasmagnusson**
Deleted Lato, now using Neue everywhere
Also set up font weights correctly

### CODE REVIEW

**Comment by rikaznismi** [comment]
Looks good, I assume semibold should be added to the header at FAQ, and Company form as well.
@mathiasmagnusson

**Comment by rikaznismi** [comment]
What is the opinion by the way opinon on the headers now. I actually think it looks better without the semibold.

**Comment by mathiasmagnusson** [comment]
> I assume semibold should be added to the header at FAQ, and Company form as well. 

Right, forgot to add that there might have been some unintended font weight changes here!

You are most likely right!

**Comment by mathiasmagnusson** [comment]
I think everything looks like on dev.ddagen.se now? @rikaznismi

**Review by rikaznismi — APPROVED** [review]
Looks good!

**Pull request merged**
