### PR TITLE
feat(app): Add search functionality 

### PR DESCRIPTION
**Pull request by ernum**

### CODE REVIEW

**Comment by rikaznismi** [comment]
@ernum 
Looks overall good, except for some issues

- It says, "Erbjuder"/"Offers", when there is no offers made. Should just be blank instead.
- Currently the search is case sensitive. In my opinion, it should not be.

**Comment by rikaznismi** [comment]
Some issues with the filter as well:
- Filter function not filtering properly
- No possible way to reset filters as well

**Comment by ernum** [comment]
> Some issues with the filter as well:
> 
> * Filter function not filtering properly

Nice catch, years were from 0-4 not 1-5 in the database.

**Review by rikaznismi — APPROVED** [review]
Looks good to me

**Pull request merged**
