### PR TITLE
Allow .eps-files for the black-white logo

### PR DESCRIPTION
**Pull request by mathiasmagnusson**
TODO: Since web browsers can't show eps files, they look like broken images.

### CODE REVIEW

**Comment by viktorrn** [comment]
Unclear of what issue this tried to solve, ill close for now and repon if the issue arises

**Comment by mathiasmagnusson** [comment]
It was requested that EPS files should be uploadable. But since they can't be viewed in most (?) web browsers, this wasn't a great fix and there wasn't enough complaints to bother i guess ^^

**Comment by viktorrn** [comment]
Was this requsted by companies to upload logos?

**Comment by mathiasmagnusson** [comment]
I would guess so, but not sure

**Pull request closed without merging**
