### PR TITLE
Fix: Even border thickness

### PR DESCRIPTION
**Pull request by rikaznismi**

### CODE REVIEW

**Review by mathiasmagnusson — COMMENTED** [review]
https://user-images.githubusercontent.com/32957299/236815041-14eac518-ce6b-4f14-89a0-d1d628211938.mp4

It's a little weird during the animation on firefox, but maybe thats fine

**Comment by ernum** [comment]
> 2023-05-08.13-39-57.mp4 
> It's a little weird during the animation on firefox, but maybe thats fine

Looks the same on Chrome for me. So, think it's fine unless @rikaznismi doesn't agree.

**Comment by mathiasmagnusson** [comment]
> Looks the same on Chrome for me.

Weird, I don't get that in chrome

**Comment by mathiasmagnusson** [comment]
And to be clear I'm talking about the border thickness during the transition

**Comment by rikaznismi** [comment]
I am also getting the same issue, chrome as well. Probably because duration is applied to thickness as well. I am having some problems with targeting transition on height, does not seem to work so far.

**Comment by rikaznismi** [comment]
@mathiasmagnusson updated the transition a bit, so the transition does not look weird in the sides of the border. And on the top of border, I removed the transition to it, since adding transition to it gave the weird effect. I think this looks better.

**Review by ernum — APPROVED** [review]
LGTM!

**Pull request merged**
