### PR TITLE
feat(app): Add sliding animation to carousel

### PR DESCRIPTION
**Pull request by ernum**

### CODE REVIEW

**Comment by rikaznismi** [comment]
@ernum 
It looks pretty good. 
Just a few things I noticed:
The three circles, are not below the image anymore, as in figma, but this looks good as well.
The arrows, to switch image are inside the image, when screen is smaller, but it looks good as well.
Lastly, I think the height of images could be increased at some ranges, for example. I think it looks a bit off, very wide, but not that tall.

bild

**Comment by ernum** [comment]
> @ernum It looks pretty good. Just a few things I noticed: The three circles, are not below the image anymore, as in figma. But I realise this is included in the carousel from flowbite, so might be hard to change this, and this looks just as good anyways.
> 
> I think the height of the images could be increased at some ranges. For example, the image below. I think it looks a bit off, very wide, but not that tall. So besides changing height, perhaps, I think it looks perfect.
> 
> bild

I think I've fixed most of the issues you mentioned. LMK if there's anything else

**Comment by rikaznismi** [comment]
@ernum 
Nice, that looks resolved. The only things lefts I have to comment about, a bit picky, is that perhaps there can be slightly  more padding in x axis, so that the image and the arrows are not that close to the border of the screen, on large screens, computers. Also, is it intentional that the arrows are not centered vertically on phones(smaller screens).

**Comment by rikaznismi** [comment]
@ernum 
It now looks a bit weird again on small screens. I think make this padding only on "xl". Then I think it looks good!

**Comment by ernum** [comment]
> @ernum It now looks a bit off again on small screens. I think make this padding only on "xl". Then I think it looks good!

Done 👍

**Review by rikaznismi — APPROVED** [review]
@ernum 
Looks good!

**Pull request merged**
