### PR TITLE
feat(app): Add grid collage component and update pages

### PR DESCRIPTION
**Pull request by ernum**

### CODE REVIEW

**Comment by ernum** [comment]
@mathiasmagnusson I can't replicate the centralisation problem. Do you still see it?

**Comment by rikaznismi** [comment]
@ernum 
What is the goal of this pull request aside from refactoring code into a component? I can see that the mobile version has changed, but personally I think the previous version of it looks better.

**Comment by ernum** [comment]
> 

The old slider on the "for companies" page does not have transparent images. That is the main difference.

**Comment by rikaznismi** [comment]
That's nice, but I noticed this too.

bild

Is the design on left intentional? I thought it looks odd when viewing from the computer, but it could look better on the phone.

**Comment by ernum** [comment]
> That's nice, but I noticed this too.
> 
> bild
> 
> Is the design on left intentional? I thought it looks odd when viewing from the computer, but it could look better on the phone.

No, missed that the mobile version did not have the same text and button. Anything else that looks weird?

**Comment by rikaznismi** [comment]
Yes, the design on the left has no x padding, or it looks very little compared to the image to the right.

**Comment by rikaznismi** [comment]
Nice, the padding looks fixed. The only issue I have left is the difference in font. The previous version is more comfortable when reading.

**Comment by ernum** [comment]
> Nice, the padding looks fixed. The only issue I have left is the difference in font. The previous version is more comfortable when reading.

Sure, updated it.

**Comment by rikaznismi** [comment]
Looks good!

**Review by rikaznismi — APPROVED** [review]

**Pull request merged**
